spring:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
greeting-service:
  greeting: "Hello PROOOOOD OH NO"
  default-value: "PROD"
