spring:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
greeting-service:
  greeting: "Hello QA ENCTROA BUG"
  default-value: "QA"
